### ISSUE TITLE
[Feature]: Login | Sign In page

### ISSUE THREAD

**Issue by jojosuelobo** [jojosuelobo/agroview-v3#1]
Make the login page in **REACT** and preferably **SASS**, but it can be done in pure **CSS**. 
_The logo image in SVG format its on path `\agroview-v3\public\LogoLight.svg`_

Figma page reference 
![Login-page](https://github.com/jojosuelobo/agroview-v3/assets/47835727/aafa7943-a03e-4a8e-b2f6-6bcfe7104d75)

**How to contribute**
You can fork the project, and create a new branch and after changes, open a pull request.

**Comment by Sky-De** [comment]
@jojosuelobo hi again, assign this to me, i will fix both of them very quickly , also as i asked in issue #2 if you don't mind please provide mobile design or at least mention how do you want it look like on mobile devices
i will fix this for you as soon as i get assignment
thanks

**Comment by jojosuelobo** [comment]
I assigned the issue to you so you can collaborate. You don't need to worry about the mobile version, just the web will be more than enough.
