### ISSUE TITLE
[Feature]: Register | Sign Up page

### ISSUE THREAD

**Issue by jojosuelobo** [jojosuelobo/agroview-v3#2]
Make the register page in **REACT** and preferably **SASS**, but it can be done in pure **CSS**. 
_The logo image in SVG format its on path `\agroview-v3\public\LogoLight.svg`_

Figma page reference 
![Registro-page](https://github.com/jojosuelobo/agroview-v3/assets/47835727/67a52aea-103f-4e5e-bdc9-32ba1327df67)

**How to contribute**
You can fork the project, and create a new branch and after changes, open a pull request.

**Comment by Sky-De** [comment]
@jojosuelobo hi, assign this to me , i would like to work on this , also if you don't mind please provide mobile design or at least mention how do you want it look like on mobile devices
i will fix this for you as soon as i get assignment
thanks

**Comment by jojosuelobo** [comment]
I assigned this issue too, same thing as login, help will be greatly appreciated
